// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiiTh-FvKSLrjDPlW7aATj0di6sPGFXK4',
    appId: '1:603340541067:android:3dc6919d21f47a3b89588e',
    messagingSenderId: '603340541067',
    projectId: 'flutter-steps-tracker-1f6e5',
    storageBucket: 'flutter-steps-tracker-1f6e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5i6FtUPxIF2ckZONHmGZ-g9owOBIgKxc',
    appId: '1:603340541067:ios:2a61da71ff2c07f489588e',
    messagingSenderId: '603340541067',
    projectId: 'flutter-steps-tracker-1f6e5',
    storageBucket: 'flutter-steps-tracker-1f6e5.appspot.com',
    iosClientId: '603340541067-t4qri6jdtndjs78j5spviqq9pgqi1rj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStepsTracker',
  );
}
